consume:
  餐饮: [ 早餐, 午餐, 晚餐, 零食, 饮料, 水果, 聚餐, 约会, 宵夜 ]
  交通: [ 公交, 地铁, 共享单车, 打的, 电车, 高铁 ]
  生活: [ 理发, 电费, 洗漱用品, 话费, 洗衣服 ]
  穿搭: [ 上衣, 快递, 裤子 ]
  医疗: [ 正畸, 核酸 ]
  运动: [ 滑板 ]
  礼物: [ 花 ]
  学习: [ 书籍, 课程, 打印 ]
  其他: [ 网吧, 快递, 买菜 ]

income: [ 学校,父母,兼职,工资,其他 ]
